version: '3.3'

services:

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
#    volumes:
#      - ./backend/static:/backend/static
    depends_on:
      - api

  api:
    build: ./backend/
    command: gunicorn sboxstore.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: